### ISSUE TITLE
Problem with AgglomerativeClustering

### ISSUE THREAD

**Issue by bumerung** [NyanNyanovich/nyan#20]
Cannot found any solution, looking for a few examples how to fix it but without success. Any idea there is my problem ?

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/nyan/nyan/send.py", line 47, in <module>
    main(**vars(args))
  File "/home/user/nyan/nyan/send.py", line 27, in main
    daemon.run(
  File "/home/user/nyan/nyan/daemon.py", line 51, in run
    self.__call__(
  File "/home/user/nyan/nyan/daemon.py", line 89, in __call__
    new_clusters = self.clusterer(annotated_docs)
  File "/home/user/nyan/nyan/clusterer.py", line 31, in __call__
    image_idx2cluster = self.find_image_duplicates(docs)
  File "/home/user/nyan/nyan/clusterer.py", line 104, in find_image_duplicates
    clustering = AgglomerativeClustering(
TypeError: AgglomerativeClustering.__init__() got an unexpected keyword argument 'affinity'

**Comment by bumerung** [comment]
Thanks a lot.
