### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by nikitashekhov** [NyanNyanovich/nyan#7]
Привет.

Используем библиотеку на MacOS, python 3.8 и python 3.9. Настроили только канал публикации ```main```, источники и другие настройки не изменены.

Кластеры не сохраняются, выдается ошибка ```ValueError: max() arg is an empty sequence```

```
./bash send.sh
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
===== New iteration =====
Reading clusters from Mongo
0 clusters loaded
Reading docs from Mongo
1336 docs loaded
Last document: 04-01-23 12:01
Warning: 0 docs from channel truexanewsua
Warning: 0 docs from channel taboo_news
Warning: 1 docs from channel agentstvonews
Warning: 0 docs from channel consultant_plus
Warning: 0 docs from channel fanimani_official
Warning: 0 docs from channel kojournal
Warning: 1 docs from channel frank_media
Warning: 1 docs from channel newsholod
Reading annotated docs from Mongo: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1336/1336 [00:01<00:00, 1158.36it/s]
1336 docs already annotated, 0 docs to annotate
1215 docs before clustering
0 updated documents
/Users/username/folder/nyan/venv/lib/python3.8/site-packages/sklearn/cluster/_agglomerative.py:983: FutureWarning: Attribute `affinity` was deprecated in version 1.2 and will be removed in 1.4. Use `metric` instead
  warnings.warn(
617 clusters overall

Issue: main, clusters after first filter: 0

Issue: tech, clusters after first filter: 0

0 clusters in all issues after filtering

0 clusters saved to file

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/username/folder/nyan/nyan/send.py", line 47, in <module>
    main(**vars(args))
  File "/Users/username/folder/nyan/nyan/send.py", line 26, in main
    daemon.run(
  File "/Users/username/folder/nyan/nyan/daemon.py", line 44, in run
    self.__call__(
  File "/Users/username/folder/nyan/nyan/daemon.py", line 97, in __call__
    saved_count = posted_clusters.save_to_mongo(mongo_config_path)
  File "/Users/username/folder/nyan/nyan/clusters.py", line 271, in save_to_mongo
    max_cluster_fetch_time = max([cl.fetch_time for cl in self.clid2cluster.values()])
ValueError: max() arg is an empty sequence
```

**Comment by NyanNyanovich** [comment]
Привет, фикс: https://github.com/NyanNyanovich/nyan/commit/dd4e56e1e39730473899d4a20aaf966b6be83458
